# This is a config for E2B sandbox template.
# You can use template ID (38r796q1uunqs5rk9ea5) or template name (kindra-nextjs-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("kindra-nextjs-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("kindra-nextjs-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('kindra-nextjs-test-2')

team_id = "ca43cf6a-7f59-4f73-9640-b51c270984e7"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "kindra-nextjs-test-2"
template_id = "38r796q1uunqs5rk9ea5"
